name: Auto Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
      - labeled

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (Fetch all history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 전체 히스토리를 가져와서 브랜치 정보를 올바르게 설정

      - name: Enable Auto-Merge
        run: |
          gh pr merge --auto --merge "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
