name: Auto Close Issue
on:
  pull_request:
    types: [closed]
jobs:
  close-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract and Close Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"

          # 브랜치명에서 /#숫자 패턴 추출
          ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '\/\#[0-9]+' | tr -d '/#')

          if [ -z "$ISSUE_NUMBER" ]; then
            echo "❌ 브랜치명에 이슈 번호가 없습니다."
            exit 1
          fi

          echo "✅ 이슈 번호: $ISSUE_NUMBER"
          gh issue close "$ISSUE_NUMBER" --comment "PR #${{ github.event.pull_request.number }} 머지로 인해 자동 종료되었습니다." --reason completed
